config/routes.rb
Rails.application.routes.draw do
  resource :session
  root "snacks#index"

  resources :flavors
  resources :snacks do
    member do
      post :swap_out
      post :swap_in
    end
  end

  resource :session, only: [:new, :create, :destroy]
  get "login", to: "sessions#new", as: :login
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy", as: :logout

  resources :passwords, param: :token
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/flavor.rb
require 'color'
class Flavor < ApplicationRecord
  has_many :snack_flavors, dependent: :destroy
  has_many :snacks, through: :snack_flavors

  def similar_to?(other)
    hex2 = other.is_a?(Flavor) ? other.color : other
    self.class.similar_color?(color, hex2)
  end

  def near_complementary_to?(other)
    hex2 = other.is_a?(Flavor) ? other.color : other
    self.class.near_complementary_color?(color, hex2)
  end

  def self.hex_to_rgb(hex)
    hex = hex.delete('#')
    r, g, b = hex.scan(/../).map { |c| c.to_i(16) }
    [r, g, b]
  end

  def self.hex_to_hue(hex)
    Color::RGB.by_hex(hex).to_hsl.h
  end

  def self.similar_color?(hex1, hex2, tolerance: 0.1)
    h1 = hex_to_hue(hex1)
    h2 = hex_to_hue(hex2)
    diff = (h1 - h2).abs
    diff <= tolerance
  end

  def self.complementary_color?(hex1, hex2, tolerance: 0.1)
    h1 = hex_to_hue(hex1)
    h2 = hex_to_hue(hex2)
    diff = (h1 - h2).abs
    (0.5 - diff).abs <= tolerance
  end
end

app/controllers/flavors_controller.rb
class FlavorsController < ApplicationController
  before_action :set_flavor, only: %i[ show edit update destroy ]

  # GET /flavors or /flavors.json
  def index
    @flavors = Flavor.all
  end

  # GET /flavors/1 or /flavors/1.json
  def show
  end

  # GET /flavors/new
  def new
    @flavor = Flavor.new
  end

  # GET /flavors/1/edit
  def edit
  end

  # POST /flavors or /flavors.json
  def create
    @flavor = Flavor.new(flavor_params)

    respond_to do |format|
      if @flavor.save
        format.html { redirect_to @flavor, notice: "Flavor was successfully created." }
        format.json { render :show, status: :created, location: @flavor }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @flavor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /flavors/1 or /flavors/1.json
  def update
    respond_to do |format|
      if @flavor.update(flavor_params)
        format.html { redirect_to @flavor, notice: "Flavor was successfully updated.", status: :see_other }
        format.json { render :show, status: :ok, location: @flavor }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @flavor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /flavors/1 or /flavors/1.json
  def destroy
    @flavor.destroy!

    respond_to do |format|
      format.html { redirect_to flavors_path, notice: "Flavor was successfully destroyed.", status: :see_other }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_flavor
      @flavor = Flavor.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def flavor_params
      params.expect(flavor: [ :name, :color, :score ])
    end
end

app/helpers/flavors_helper.rb
module FlavorsHelper
end

app/views/flavors/_flavor.html.haml
%div{id: dom_id(flavor)}
  %p
    %strong Name:
    = flavor.name

  %p
    %strong Color:
    = flavor.color

  %p
    %strong Score:
    = flavor.score

app/views/flavors/_form.html.haml
= form_with(model: flavor) do |form|
  - if flavor.errors.any?
    %div{style: "color: red"}
      %h2= "#{pluralize(flavor.errors.count, "error")} prohibited this flavor from being saved:"

      %ul
        - flavor.errors.each do |error|
          %li= error.full_message

  %div
    = form.label :name, style: "display: block"
    = form.text_field :name

  %div
    = form.label :color, style: "display: block"
    = form.text_field :color

  %div
    = form.label :score, style: "display: block"
    = form.text_field :score

  %div
    = form.submit

app/views/flavors/edit.html.haml
- content_for :title, "Editing flavor"

%h1 Editing flavor

= render "form", flavor: @flavor

%br

%div
  = link_to "Show this flavor", @flavor
  |
  = link_to "Back to flavors", flavors_path

app/views/flavors/index.html.haml
%p{style: "color: green"}= notice

- content_for :title, "Flavors"

%h1 Flavors

%div{id: "flavors"}
  - @flavors.each do |flavor|
    = render flavor
    %p
      = link_to "Show this flavor", flavor

= link_to "New flavor", new_flavor_path

app/views/flavors/new.html.haml
- content_for :title, "New flavor"

%h1 New flavor

= render "form", flavor: @flavor

%br

%div
  = link_to "Back to flavors", flavors_path

app/views/flavors/show.html.haml
%p{style: "color: green"}= notice

= render @flavor

%div
  = link_to "Edit this flavor", edit_flavor_path(@flavor)
  |
  = link_to "Back to flavors", flavors_path

  = button_to "Destroy this flavor", @flavor, method: :delete