config/routes.rb
Rails.application.routes.draw do
  resource :session
  root "snacks#index"

  resources :flavors
  resources :snacks do
    member do
      post :swap_out
      post :swap_in
    end
  end

  resource :session, only: [:new, :create, :destroy]
  get "login", to: "sessions#new", as: :login
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy", as: :logout

  resources :passwords, param: :token
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/views/shared/_navbar.html.haml
%nav.navbar.navbar-expand-lg
  .container-fluid
    = link_to "Snack App", root_path, class: "navbar-brand"
    %ul.navbar-nav.ms-auto
      - if authenticated?
        %li.nav-item
          %span.nav-link.text-light.me-2
            Hello #{current_user&.name.presence || current_user&.email}
        %li.nav-item
          = button_to "Logout", logout_path, method: :delete, class: "btn btn-link nav-link", form: { "data-turbo-confirm": "Are you sure you want to log out?" }
      - else
        %li.nav-item
          = link_to "Login", new_session_path, class: "nav-link"

app/views/shared/_notice.html.haml
.alert.alert-success{ role: "alert" }
  = notice